import Head from 'next/head';
import Image from 'next/image';
// import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import InvoiceList from '@/components/InvoiceList';
import allInvoices from '@/data/data.json';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <main className="main">
          <div className="sidebar"></div>
          <div className="center">
            <header>
              <div className="title">
                <h1>Invoices</h1>
                <p>There are {allInvoices.length} total invoices</p>
              </div>
              <div className="right">
                <div className="filter">Filter by status</div>
                <div className="new-invoice">
                  <button>New Invoice</button>
                </div>
              </div>
            </header>
            <div className="invoices-list">
              <InvoiceList invoices={allInvoices} />
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
